"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Package, Plus } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { api, formatPrice, type Product } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { Button, StateMessage } from "@/components/ui";
export default function ProductDetailPage() { const params = useParams<{ productId: string }>(); const router = useRouter(); const { customer } = useAuth(); const [product, setProduct] = useState<Product | null>(null); const [quantity, setQuantity] = useState(1); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); useEffect(() => { api.product(params.productId).then(setProduct).catch(e => setMessage(e.message)); }, [params.productId]); async function add() { if (!product || !customer) return; setLoading(true); setMessage(""); try { await api.addToCart(customer.id, { product_id: product.id, name: product.name, quantity, unit_price_paise: product.price_paise }); router.push("/cart"); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to add item"); } finally { setLoading(false); } } if (message && !product) return <div className="mx-auto max-w-7xl px-5 py-16"><StateMessage>{message}</StateMessage></div>; if (!product) return <div className="grid min-h-[60vh] place-items-center text-sm text-[var(--muted-foreground)]">Loading product...</div>; return <div className="mx-auto max-w-7xl px-5 py-10 lg:px-8 lg:py-16"><Link href="/products" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--muted-foreground)] hover:text-[var(--primary)]"><ArrowLeft size={16} />Back to collection</Link><div className="mt-10 grid gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:gap-20"><div className="grid min-h-[420px] place-items-center bg-[var(--surface-muted)]"><Package size={100} strokeWidth={0.8} className="text-[var(--primary)]" /></div><div className="flex flex-col justify-center"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--primary)]">{product.sku}</p><h1 className="mt-3 font-display text-4xl font-bold tracking-tight">{product.name}</h1><p className="mt-5 text-2xl font-semibold">{formatPrice(product.price_paise, product.currency)}</p><p className="mt-6 max-w-md text-sm leading-7 text-[var(--muted-foreground)]">{product.description || "A considered addition to your everyday."}</p><p className="mt-8 text-sm font-semibold">{product.available_quantity > 0 ? `${product.available_quantity} available` : "Currently unavailable"}</p><div className="mt-5 flex gap-3"><div className="flex h-11 items-center border border-[var(--border)]"><button aria-label="Decrease quantity" onClick={() => setQuantity(Math.max(1, quantity - 1))} className="h-full w-10 text-lg">−</button><span className="w-8 text-center text-sm">{quantity}</span><button aria-label="Increase quantity" onClick={() => setQuantity(Math.min(product.available_quantity || 1, quantity + 1))} className="h-full w-10 text-lg">+</button></div><Button onClick={add} loading={loading} disabled={product.available_quantity < 1}><Plus size={16} />Add to cart</Button></div>{message && <p role="alert" className="mt-4 text-sm text-[var(--destructive)]">{message}</p>}</div></div></div>; }
