"use client";
import { FormEvent, useState } from "react";
import { CartPanel } from "../components/CartPanel";
import { Conversation } from "../components/Conversation";
import { Message, Product } from "../components/types";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
type RazorpayResponse = { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string };
declare global { interface Window { Razorpay?: new (options: Record<string, unknown>) => { open: () => void } } }

export default function Home() {
  const [messages, setMessages] = useState<Message[]>([{ role: "agent", text: "What can I help you find today? Tell me what matters—comfort, battery, budget, or how you’ll use it." }]);
  const [input, setInput] = useState(""); const [cart, setCart] = useState<Product[]>([]); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const openRazorpay = async (payment: { order_id: string; amount: number; currency: string; key_id: string }) => {
    if (!window.Razorpay) { setNotice("Razorpay Checkout could not load. Please check your connection."); return; }
    new window.Razorpay({ key: payment.key_id, amount: payment.amount * 100, currency: payment.currency, order_id: payment.order_id, name: "Lumio Store", description: "Secure order payment", handler: async (response: RazorpayResponse) => {
      const result = await fetch(`${API}/api/payment/verify`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ order_id: response.razorpay_order_id, payment_id: response.razorpay_payment_id, signature: response.razorpay_signature }) });
      setNotice(result.ok ? "Payment verified. Your order is confirmed." : "Payment verification failed. No order was completed."); if (result.ok) setCart([]);
    }, theme: { color: "#3156e8" } }).open();
  };
  const send = async (message = input) => { if (!message.trim() || busy) return; setBusy(true); setInput(""); setMessages(all => [...all, { role: "user", text: message }]); try {
    const response = await fetch(`${API}/api/chat`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message }) }); const data = await response.json();
    setMessages(all => [...all, { role: "agent", text: data.message, products: data.products, blocked: data.blocked }]); if (data.cart) setCart(data.cart); if (data.payment?.mode === "razorpay") await openRazorpay(data.payment);
  } catch { setMessages(all => [...all, { role: "agent", text: "I can’t reach the store service right now. Please make sure the backend is running.", blocked: true }]); } finally { setBusy(false); } };
  const add = async (product: Product) => { const response = await fetch(`${API}/api/cart`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ product_id: product.id }) }); const data = await response.json(); if (data.cart) { setCart(data.cart); setNotice(`${product.name} added to your cart.`); } };
  return <main className="min-h-screen bg-[#f7f8fc] text-[#18214d]"><script src="https://checkout.razorpay.com/v1/checkout.js" />
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#3156e8] font-bold text-white">L</div><div><h1 className="font-bold tracking-tight">Lumio <span className="font-normal text-slate-400">Store</span></h1><p className="text-[10px] font-semibold uppercase tracking-wider text-[#6471cf]">Powered by Razorpay</p></div></div><div className="hidden items-center gap-6 text-sm text-slate-500 sm:flex"><span>Curated tech</span><span>Secure checkout</span><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">● Payments protected</span></div></div></header>
    <div className="mx-auto max-w-7xl px-5 py-8 lg:px-8"><section className="mb-6 rounded-3xl bg-[#17296d] px-6 py-7 text-white lg:px-9"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#aebcff]">Conversational commerce</p><div className="mt-2 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-semibold tracking-tight lg:text-3xl">Shop with a little more context.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#c9d2ff]">Ask for recommendations naturally. Your assistant checks the merchant’s live catalog before every answer.</p></div><button onClick={() => send("Show me popular products for everyday use")} className="shrink-0 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-[#243eab]">Explore products</button></div></section>
      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold">Shopping assistant</h2><p className="mt-0.5 text-xs text-slate-500">Live catalogue · Secure actions</p></div><span className="rounded-full bg-[#eef1ff] px-3 py-1.5 text-xs font-medium text-[#3156e8]">Online</span></div><div className="h-[530px] overflow-y-auto p-5 lg:p-6"><Conversation messages={messages} onAdd={add} /></div><form onSubmit={(event: FormEvent) => { event.preventDefault(); send(); }} className="border-t border-slate-100 bg-white p-4"><div className="flex gap-2 rounded-xl border border-slate-200 bg-[#fafbff] p-1.5 focus-within:border-[#6471cf] focus-within:ring-2 focus-within:ring-[#dce2ff]"><input value={input} onChange={event => setInput(event.target.value)} placeholder="Try: Need something lightweight for travel" className="min-w-0 flex-1 bg-transparent px-3 text-sm outline-none placeholder:text-slate-400" /><button disabled={busy} className="rounded-lg bg-[#3156e8] px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{busy ? "Thinking…" : "Send"}</button></div></form></section>
        <div className="space-y-4"><CartPanel cart={cart} onCheckout={() => send("I want to checkout with my cart")} />{notice ? <p className="rounded-xl border border-[#cbd5ff] bg-[#eef1ff] p-3 text-xs leading-5 text-[#263eaa]">{notice}</p> : null}<p className="px-2 text-xs leading-5 text-slate-500">Prices, availability, totals and payment verification are handled by the store backend. The assistant can recommend, but cannot alter financial data.</p></div></div></div></main>;
}
