"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { CartPanel } from "../components/CartPanel";
import { Conversation } from "../components/Conversation";
import { ProductCard } from "../components/ProductCard";
import { Message, Product } from "../components/types";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
const PREVIEW_PRODUCTS: Product[] = [
  { id: "soundmax-pro", name: "SoundMax Pro ANC", description: "Hybrid noise cancellation with 35-hour battery.", price: 2499, stock: 12, category: "audio" },
  { id: "nova-watch", name: "Nova Watch S", description: "AMOLED fitness watch with seven-day battery.", price: 3499, stock: 9, category: "wearables" },
  { id: "chargecube-65", name: "ChargeCube 65W", description: "Compact GaN fast charger for your essentials.", price: 2199, stock: 20, category: "accessories" },
  { id: "sky-keyboard", name: "SkyKeys Mini", description: "Low-profile wireless keyboard for focused work.", price: 2699, stock: 11, category: "work" },
  { id: "echo-buds", name: "Echo Buds Lite", description: "Pocket-sized earbuds with clear calls.", price: 1799, stock: 24, category: "audio" },
  { id: "glide-mouse", name: "Glide Mouse", description: "Silent-click ergonomic mouse with precise scroll.", price: 1199, stock: 28, category: "work" },
];
type RazorpayResponse = { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string };
declare global { interface Window { Razorpay?: new (options: Record<string, unknown>) => { open: () => void } } }

export default function Home() {
  const [products, setProducts] = useState<Product[]>(PREVIEW_PRODUCTS); const [category, setCategory] = useState("all"); const [messages, setMessages] = useState<Message[]>([{ role: "agent", text: "Tell me what you need. I’ll narrow down the live store catalogue and help you choose." }]);
  const [input, setInput] = useState(""); const [cart, setCart] = useState<Product[]>([]); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [assistantOpen, setAssistantOpen] = useState(false);
  useEffect(() => { fetch(`${API}/api/catalog`).then(response => response.json()).then(data => setProducts(data.products || [])).catch(() => setNotice("Store catalogue is unavailable. Start the backend to load products.")); }, []);
  const visibleProducts = useMemo(() => category === "all" ? products : products.filter(product => product.category === category), [products, category]);
  const openRazorpay = async (payment: { order_id: string; amount: number; currency: string; key_id: string }) => { if (!window.Razorpay) { setNotice("Razorpay Checkout could not load. Please check your connection."); return; } new window.Razorpay({ key: payment.key_id, amount: payment.amount * 100, currency: payment.currency, order_id: payment.order_id, name: "Lumio Store", description: "Secure order payment", handler: async (response: RazorpayResponse) => { const result = await fetch(`${API}/api/payment/verify`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ order_id: response.razorpay_order_id, payment_id: response.razorpay_payment_id, signature: response.razorpay_signature }) }); setNotice(result.ok ? "Payment verified. Your order is confirmed." : "Payment verification failed. No order was completed."); if (result.ok) setCart([]); }, theme: { color: "#3156e8" } }).open(); };
  const send = async (message = input) => { if (!message.trim() || busy) return; setBusy(true); setInput(""); setAssistantOpen(true); setMessages(all => [...all, { role: "user", text: message }]); try { const response = await fetch(`${API}/api/chat`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message }) }); const data = await response.json(); setMessages(all => [...all, { role: "agent", text: data.message, products: data.products, blocked: data.blocked }]); if (data.products) setProducts(existing => { const ids = new Set(existing.map(product => product.id)); return [...existing, ...data.products.filter((product: Product) => !ids.has(product.id))]; }); if (data.cart) setCart(data.cart); if (data.payment?.mode === "razorpay") await openRazorpay(data.payment); } catch { setMessages(all => [...all, { role: "agent", text: "I can’t reach the store service right now. Please make sure the backend is running.", blocked: true }]); } finally { setBusy(false); } };
  const add = async (product: Product) => { const response = await fetch(`${API}/api/cart`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ product_id: product.id }) }); const data = await response.json(); if (data.cart) { setCart(data.cart); setNotice(`${product.name} is in your cart.`); } };
  const categories = ["all", "audio", "wearables", "accessories", "work"];
  return <main className="min-h-screen bg-[#f7f8fc] text-[#142046]"><script src="https://checkout.razorpay.com/v1/checkout.js" />
    <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#3156e8] text-lg font-bold text-white shadow-lg shadow-[#3156e8]/30">L</div><div><h1 className="font-bold tracking-tight">Lumio</h1><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#6471cf]">A smarter way to shop</p></div></div><nav className="hidden gap-7 text-sm font-medium text-slate-500 md:flex"><a href="#shop" className="text-[#3156e8]">Shop</a><button onClick={() => setAssistantOpen(true)}>Ask Lumio</button><button onClick={() => setAssistantOpen(true)}>Orders</button></nav><button onClick={() => setAssistantOpen(true)} className="rounded-xl bg-[#eef1ff] px-3 py-2 text-xs font-semibold text-[#3156e8]">Cart · {cart.length}</button></div></header>
    <div className="mx-auto max-w-7xl px-5 py-7 lg:px-8"><section className="hero-grid relative overflow-hidden rounded-[28px] bg-[#182d80] px-6 py-9 text-white lg:px-10 lg:py-12"><div className="relative z-10 max-w-xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#b9c7ff]">Lumio essentials</p><h2 className="mt-3 text-3xl font-semibold tracking-tight lg:text-5xl">Tech that fits<br />your everyday.</h2><p className="mt-4 max-w-md text-sm leading-6 text-[#d7deff]">Discover considered electronics for travel, work, movement and downtime—without the endless scroll.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={() => document.getElementById("shop")?.scrollIntoView({ behavior: "smooth" })} className="rounded-xl bg-white px-4 py-3 text-sm font-semibold text-[#2443bb]">Shop the edit</button><button onClick={() => { setAssistantOpen(true); send("Help me choose the right product for my needs"); }} className="rounded-xl border border-white/30 px-4 py-3 text-sm font-semibold text-white">Ask for a recommendation</button></div></div><div className="hero-device hero-device-one" /><div className="hero-device hero-device-two" /><div className="hero-ring" /></section>
      <section id="shop" className="mt-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#6471cf]">The store edit</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">Find your next favourite.</h2></div><div className="flex gap-2 overflow-x-auto pb-1">{categories.map(item => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-medium capitalize transition ${category === item ? "bg-[#3156e8] text-white" : "border border-slate-200 bg-white text-slate-600 hover:border-[#3156e8]"}`}>{item === "all" ? "Everything" : item}</button>)}</div></div>
        <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visibleProducts.map(product => <ProductCard key={product.id} product={product} onAdd={add} />)}</div></section></div>
    <div className={`fixed inset-0 z-30 ${assistantOpen ? "pointer-events-auto" : "pointer-events-none"}`}><div onClick={() => setAssistantOpen(false)} className={`absolute inset-0 bg-[#08123d]/30 transition-opacity ${assistantOpen ? "opacity-100" : "opacity-0"}`} /><aside className={`absolute right-0 top-0 flex h-full w-full max-w-[430px] flex-col bg-[#f8f9ff] shadow-2xl transition-transform duration-300 ${assistantOpen ? "translate-x-0" : "translate-x-full"}`}><div className="flex items-center justify-between border-b border-slate-200 bg-white px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#3156e8] font-bold text-white">L</div><div><h2 className="font-semibold">Lumio assistant</h2><p className="text-xs text-emerald-600">● Live catalogue connected</p></div></div><button onClick={() => setAssistantOpen(false)} className="rounded-lg px-2 py-1 text-lg text-slate-400">×</button></div><div className="flex-1 overflow-y-auto p-5"><Conversation messages={messages} onAdd={add} /></div><div className="border-t border-slate-200 bg-white p-4"><CartPanel cart={cart} onCheckout={() => send("I want to checkout with my cart")} />{notice ? <p className="mt-3 rounded-xl bg-[#eef1ff] p-3 text-xs text-[#263eaa]">{notice}</p> : null}<form onSubmit={(event: FormEvent) => { event.preventDefault(); send(); }} className="mt-3 flex gap-2"><input value={input} onChange={event => setInput(event.target.value)} placeholder="Ask Lumio anything…" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-[#3156e8]" /><button disabled={busy} className="rounded-xl bg-[#3156e8] px-4 text-sm font-semibold text-white disabled:opacity-60">{busy ? "…" : "Send"}</button></form></div></aside></div>
  </main>;
}
